### PR TITLE
Added Dockerfiles for UBI-based containers

### PR DESCRIPTION
**Pull request by Demostenes777**
This PR adds Dockerfiles for open5gs and open5gs-webui based on Red Hat's UBI image.

### CODE REVIEW

**Comment by cgiraldo** [comment]
I have login into redhat registry correctly but I am not able to build open5gs ubi:

```
 => ERROR [stage-1  3/13] RUN microdnf install --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms -y         libtalloc-devel                                                                            0.5s
------                                                                                                                                                                                                           
 > [stage-1  3/13] RUN microdnf install --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms -y         libtalloc-devel:                                                                                       
#0 0.482                                                                                                                                                                                                         
#0 0.482 (microdnf:1): librhsm-WARNING **: 05:39:31.722: Found 0 entitlement certificates                                                                                                                        
#0 0.485 
#0 0.485 (microdnf:1): librhsm-WARNING **: 05:39:31.725: Found 0 entitlement certificates
#0 0.488 error: repo codeready-builder-for-rhel-9-x86_64-rpms not found
------
Dockerfile.ubi:79
```

**Comment by cgiraldo** [comment]
In order to make the redhat CI steps to work for a fork, the fork repository must include the following github secrets:

- REDHAT_USERNAME
- REDHAT_PASSWORD

We already have this secrets in openverso-images repo with a service account to login into registry.redhat.io, but since your repo is a fork, the on pull_request action does not have access to them.

**Comment by Demostenes777** [comment]
> I have login into redhat registry correctly but I am not able to build open5gs ubi:
> 
> ```
>  => ERROR [stage-1  3/13] RUN microdnf install --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms -y         libtalloc-devel                                                                            0.5s
> ------                                                                                                                                                                                                           
>  > [stage-1  3/13] RUN microdnf install --enablerepo=codeready-builder-for-rhel-9-$(arch)-rpms -y         libtalloc-devel:                                                                                       
> #0 0.482                                                                                                                                                                                                         
> #0 0.482 (microdnf:1): librhsm-WARNING **: 05:39:31.722: Found 0 entitlement certificates                                                                                                                        
> #0 0.485 
> #0 0.485 (microdnf:1): librhsm-WARNING **: 05:39:31.725: Found 0 entitlement certificates
> #0 0.488 error: repo codeready-builder-for-rhel-9-x86_64-rpms not found
> ------
> Dockerfile.ubi:79
> ```

I am curious about this because the same repo is used in a previous step, line 16. I have run it now and it has worked for me. Can you please check again, just in case it was a temporary problem with the repo?

**Comment by Demostenes777** [comment]
Just to give an update on the topic. The build of the image works correctly if it is done in a RHEL 9 machine. I am currently investigating and dealing with the installation of some libraries when the built is done in an Ubuntu machine.

**Comment by cgiraldo** [comment]
To allow github actions to build the ubi image, you need to include a secret in your github repository to be able to dowload the ubi9-minimal from registry.redhat.io.

The secrets must be:

`REDHAT_USERNAME` and `REDHAT_PASSWORD` with a  token with read permissions to registry.redhat.io.

https://github.com/Gradiant/openverso-images/blob/f4a115049687e636f022c6312bbe1022402f8a53/.github/workflows/build.yml#L78

**Comment by cgiraldo** [comment]
Closed since cannot build in a machine without a REDHAT subscription.

**Pull request closed without merging**
